# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import RiskScore_pb2 as RiskScore__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in RiskScore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiskScoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateRiskScore = channel.unary_stream(
            '/RiskScorePackage.RiskScore/CalculateRiskScore',
            request_serializer=RiskScore__pb2.RiskScoreRequest.SerializeToString,
            response_deserializer=RiskScore__pb2.RiskScoreUpdate.FromString,
            _registered_method=True)


class RiskScoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateRiskScore(self, request, context):
        """rpc CalculateRiskScore (RiskScoreRequest) returns (RiskScoreUpdate);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskScoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CalculateRiskScore': grpc.unary_stream_rpc_method_handler(
            servicer.CalculateRiskScore,
            request_deserializer=RiskScore__pb2.RiskScoreRequest.FromString,
            response_serializer=RiskScore__pb2.RiskScoreUpdate.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RiskScorePackage.RiskScore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'RiskScorePackage.RiskScore', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class RiskScore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateRiskScore(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RiskScorePackage.RiskScore/CalculateRiskScore',
            RiskScore__pb2.RiskScoreRequest.SerializeToString,
            RiskScore__pb2.RiskScoreUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
