# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TaskList.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'TaskList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eTaskList.proto\x12\x0fTaskListPackage\"\x07\n\x05\x45mpty\"7\n\x11\x43reateTaskMessage\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12TaskCreatedMessage\x12\n\n\x02id\x18\x01 \x01(\r\"P\n\x0bTaskMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\">\n\x0fTaskListMessage\x12+\n\x05tasks\x18\x01 \x03(\x0b\x32\x1c.TaskListPackage.TaskMessage\"!\n\x13\x43ompleteTaskMessage\x12\n\n\x02id\x18\x01 \x01(\r\"8\n\x10RiskScoreRequest\x12\x14\n\x0cmanufacturer\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\"\x81\x01\n\x0fRiskScoreUpdate\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x01\x12\x12\n\nrisk_score\x18\x03 \x01(\x01\x12\x14\n\x0crecord_count\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x11\n\tcompleted\x18\x06 \x01(\x08\x32\xd1\x02\n\x08TaskList\x12U\n\nCreateTask\x12\".TaskListPackage.CreateTaskMessage\x1a#.TaskListPackage.TaskCreatedMessage\x12\x45\n\tListTasks\x12\x16.TaskListPackage.Empty\x1a .TaskListPackage.TaskListMessage\x12L\n\x0c\x43ompleteTask\x12$.TaskListPackage.CompleteTaskMessage\x1a\x16.TaskListPackage.Empty\x12Y\n\x12\x43\x61lculateRiskScore\x12!.TaskListPackage.RiskScoreRequest\x1a .TaskListPackage.RiskScoreUpdateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TaskList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_CREATETASKMESSAGE']._serialized_start=44
  _globals['_CREATETASKMESSAGE']._serialized_end=99
  _globals['_TASKCREATEDMESSAGE']._serialized_start=101
  _globals['_TASKCREATEDMESSAGE']._serialized_end=133
  _globals['_TASKMESSAGE']._serialized_start=135
  _globals['_TASKMESSAGE']._serialized_end=215
  _globals['_TASKLISTMESSAGE']._serialized_start=217
  _globals['_TASKLISTMESSAGE']._serialized_end=279
  _globals['_COMPLETETASKMESSAGE']._serialized_start=281
  _globals['_COMPLETETASKMESSAGE']._serialized_end=314
  _globals['_RISKSCOREREQUEST']._serialized_start=316
  _globals['_RISKSCOREREQUEST']._serialized_end=372
  _globals['_RISKSCOREUPDATE']._serialized_start=375
  _globals['_RISKSCOREUPDATE']._serialized_end=504
  _globals['_TASKLIST']._serialized_start=507
  _globals['_TASKLIST']._serialized_end=844
# @@protoc_insertion_point(module_scope)
