# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.TaskList_pb2 as TaskList__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in TaskList_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/TaskListPackage.TaskList/CreateTask',
                request_serializer=TaskList__pb2.CreateTaskMessage.SerializeToString,
                response_deserializer=TaskList__pb2.TaskCreatedMessage.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/TaskListPackage.TaskList/ListTasks',
                request_serializer=TaskList__pb2.Empty.SerializeToString,
                response_deserializer=TaskList__pb2.TaskListMessage.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/TaskListPackage.TaskList/CompleteTask',
                request_serializer=TaskList__pb2.CompleteTaskMessage.SerializeToString,
                response_deserializer=TaskList__pb2.Empty.FromString,
                _registered_method=True)
        self.CalculateRiskScore = channel.unary_unary(
                '/TaskListPackage.TaskList/CalculateRiskScore',
                request_serializer=TaskList__pb2.RiskScoreRequest.SerializeToString,
                response_deserializer=TaskList__pb2.RiskScoreUpdate.FromString,
                _registered_method=True)


class TaskListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRiskScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=TaskList__pb2.CreateTaskMessage.FromString,
                    response_serializer=TaskList__pb2.TaskCreatedMessage.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=TaskList__pb2.Empty.FromString,
                    response_serializer=TaskList__pb2.TaskListMessage.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=TaskList__pb2.CompleteTaskMessage.FromString,
                    response_serializer=TaskList__pb2.Empty.SerializeToString,
            ),
            'CalculateRiskScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRiskScore,
                    request_deserializer=TaskList__pb2.RiskScoreRequest.FromString,
                    response_serializer=TaskList__pb2.RiskScoreUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskListPackage.TaskList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TaskListPackage.TaskList', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskListPackage.TaskList/CreateTask',
            TaskList__pb2.CreateTaskMessage.SerializeToString,
            TaskList__pb2.TaskCreatedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskListPackage.TaskList/ListTasks',
            TaskList__pb2.Empty.SerializeToString,
            TaskList__pb2.TaskListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskListPackage.TaskList/CompleteTask',
            TaskList__pb2.CompleteTaskMessage.SerializeToString,
            TaskList__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateRiskScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskListPackage.TaskList/CalculateRiskScore',
            TaskList__pb2.RiskScoreRequest.SerializeToString,
            TaskList__pb2.RiskScoreUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
